<?php

namespace AppBundle\Repository;

/**
 * ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileRepository extends \Doctrine\ORM\EntityRepository
{
    public function findProfileIdByUser($user)
    {
        $em = $this->getEntityManager();

        // create query
        $qb = $em->createQueryBuilder()
            ->select('p.id')
            ->from('AppBundle:Profile', 'p')
            ->where('p.user = :user')
            ->setParameter(':user', $user)
            ->getQuery()
            ->getArrayResult();
        ;

        return current($qb);
    }
}
